# ============================================================================
# STREAMLIT CONFIGURATION
# Total Health Conferencing - LOR/LOA Generator
# ============================================================================

[theme]
# Professional color scheme matching Total Health branding
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[server]
# Server settings
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200

[browser]
# Browser settings
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[runner]
# Performance settings
magicEnabled = true
fastReruns = true
